name: klippa_identity_validation_sdk
description: Allows you to do identity validation with the Klippa Identity Validation SDK from Flutter apps.
version: 0.0.1
author:
homepage: https://github.com/klippa-app/flutter-klippa-identity-verification-sdk

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.klippa.identity_verification.klippa_identity_validation_sdk
        pluginClass: KlippaIdentityValidationSdkPlugin
      ios:
        pluginClass: KlippaIdentityValidationSdkPlugin

