name: Build CI

# Trigger the workflow on push or pull request
on: [push]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.2'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk
        working-directory: ./example
  build-osx:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.2'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk
        working-directory: ./example
      - run: flutter build appbundle
        working-directory: ./example
